flowchart LR

subgraph 0["apps"]
subgraph 1["artists"]
subgraph 2["core"]
subgraph 3["modules"]
subgraph 4["auth"]
subgraph 5["client"]
6["get-auth-client-cookie.tsx"]
9["login-post-fetch.tsx"]
A["logout-post-fetch.tsx"]
B["use-auth.tsx"]
end
subgraph 7["domain"]
8["token.tsx"]
O["delete-auth-cookie.tsx"]
P["errors.tsx"]
Q["login-dto.tsx"]
R["login-use-case.tsx"]
S["set-auth-cookie.tsx"]
T["logout-use-case.tsx"]
U["token-public-dto.tsx"]
V["user.tsx"]
end
subgraph C["components"]
subgraph D["anonymous-content"]
E["anonymous-content.tsx"]
end
subgraph F["login-form"]
G["login-form.tsx"]
H["use-login-form.tsx"]
end
subgraph I["register-form"]
J["register-form.tsx"]
end
subgraph K["auth-section"]
L["auth-section.tsx"]
end
subgraph M["members-content"]
N["members-content.tsx"]
end
end
subgraph W["server"]
X["http-response.tsx"]
Y["login-get-controller.tsx"]
Z["login-post-controller.tsx"]
10["logout-get-controller.tsx"]
11["logout-post-controller.tsx"]
end
end
subgraph 12["environment"]
13["environment-display.tsx"]
14["use-environment.tsx"]
end
subgraph 15["landing"]
16["page.tsx"]
end
end
end
17["settings.tsx"]
end
end
6-->8
B-->6
B-->9
B-->A
E-->G
E-->J
G-->H
H-->B
L-->B
L-->E
L-->N
N-->B
O-->8
R-->P
R-->S
R-->8
S-->8
T-->O
T-->P
Y-->X
Z-->P
Z-->R
Z-->X
10-->X
11-->T
11-->X
13-->14
16-->17
16-->L
16-->13
