flowchart LR

subgraph 0["apps"]
subgraph 1["artists"]
subgraph 2["core"]
subgraph 3["modules"]
subgraph 4["auth"]
subgraph 5["client"]
6["get-auth-client-cookie.tsx"]
9["login-post-fetch-result.tsx"]
C["logout-post-fetch.tsx"]
D["use-auth.tsx"]
end
subgraph 7["domain"]
8["token.tsx"]
S["login-dto.tsx"]
T["login-use-case.tsx"]
subgraph U["service"]
V["get-from-json.tsx"]
X["save-token.tsx"]
Y["validate-dto.tsx"]
10["verify-credentials.tsx"]
13["delete-auth-cookie.tsx"]
end
12["logout-use-case.tsx"]
14["token-public-dto.tsx"]
15["user.tsx"]
end
subgraph A["errors"]
B["internal-error.tsx"]
W["bad-json-format-error.tsx"]
Z["bad-dto-format-error.tsx"]
11["bad-credentials-error.tsx"]
16["not-found-error.tsx"]
end
subgraph G["components"]
subgraph H["anonymous-content"]
I["anonymous-content.tsx"]
end
subgraph J["login-form"]
K["login-form.tsx"]
L["use-login-form.tsx"]
end
subgraph M["register-form"]
N["register-form.tsx"]
end
subgraph O["auth-section"]
P["auth-section.tsx"]
end
subgraph Q["members-content"]
R["members-content.tsx"]
end
end
subgraph 17["server"]
subgraph 18["controllers"]
19["login-get-controller.tsx"]
1B["login-post-controller.tsx"]
1C["logout-get-controller.tsx"]
1D["logout-post-controller.tsx"]
end
1A["http-response.tsx"]
end
end
subgraph 1E["environment"]
1F["environment-display.tsx"]
1G["use-environment.tsx"]
end
subgraph 1H["landing"]
1I["page.tsx"]
end
end
end
subgraph E["utils"]
F["use-effect-once.tsx"]
end
1J["settings.tsx"]
end
end
6-->8
9-->8
9-->B
D-->F
D-->6
D-->9
D-->C
I-->K
I-->N
K-->L
L-->D
P-->D
P-->I
P-->R
R-->D
T-->B
T-->V
T-->X
T-->Y
T-->10
V-->W
X-->B
X-->8
Y-->Z
10-->11
12-->B
12-->13
13-->8
19-->1A
1B-->T
1B-->1A
1C-->1A
1D-->12
1D-->1A
1F-->1G
1I-->1J
1I-->P
1I-->1F
