flowchart LR

subgraph 0["apps"]
subgraph 1["artists"]
subgraph 2["app"]
subgraph 3["api"]
subgraph 4["auth"]
subgraph 5["login"]
6["route.ts"]
end
subgraph T["logout"]
U["route.ts"]
end
end
end
subgraph 11["components"]
12["icons.tsx"]
subgraph 13["layout"]
14["app-footer.tsx"]
15["app-header.tsx"]
16["app-layout.tsx"]
17["app-page.tsx"]
18["app-shell.tsx"]
end
19["product-card.tsx"]
end
subgraph 1A["home"]
1B["page.tsx"]
end
1E["layout.tsx"]
1F["globals.css"]
1G["page.tsx"]
subgraph 1H["store-config"]
1I["get-store-config.tsx"]
1J["store-config-repository.tsx"]
1M["get-stores.tsx"]
1N["store-config.tsx"]
end
subgraph 1O["stores"]
subgraph 1P["[storeDomain]"]
1Q["layout.tsx"]
1R["page.tsx"]
end
end
end
subgraph 7["core"]
subgraph 8["modules"]
subgraph 9["auth"]
subgraph A["server"]
subgraph B["login"]
subgraph C["controllers"]
D["login-get-controller.tsx"]
F["login-post-controller.tsx"]
end
end
E["http-response.tsx"]
subgraph V["logout"]
subgraph W["controllers"]
X["logout-get-controller.tsx"]
Y["logout-post-controller.tsx"]
end
end
end
subgraph G["domain"]
H["login-use-case.tsx"]
subgraph K["auth-service"]
L["save-token.tsx"]
10["delete-auth-cookie.tsx"]
end
N["token.tsx"]
O["login-dto.tsx"]
R["user.tsx"]
Z["logout-use-case.tsx"]
end
subgraph I["errors"]
J["server-error.tsx"]
M["internal-error.tsx"]
P["bad-dto-format-error.tsx"]
Q["bad-json-format-error.tsx"]
S["bad-credentials-error.tsx"]
end
end
subgraph 1C["home"]
1D["page.tsx"]
end
end
end
subgraph 1K["utils"]
1L["fake-timeout.tsx"]
end
end
end
6-->D
6-->F
D-->E
F-->H
F-->E
H-->J
H-->L
H-->O
H-->R
L-->M
L-->N
O-->P
O-->Q
R-->S
U-->X
U-->Y
X-->E
Y-->Z
Y-->E
Z-->J
Z-->10
10-->N
16-->14
16-->15
16-->17
16-->18
1B-->1D
1D-->19
1E-->1F
1G-->1B
1I-->1J
1J-->1L
1M-->1J
1Q-->16
1Q-->1I
1R-->1L
1R-->19
1R-->1M
