flowchart LR

subgraph 0["apps"]
subgraph 1["artists"]
subgraph 2["app"]
subgraph 3["api"]
subgraph 4["auth"]
subgraph 5["login"]
6["route.ts"]
end
subgraph T["logout"]
U["route.ts"]
end
end
end
11["layout.tsx"]
12["page.tsx"]
end
subgraph 7["core"]
subgraph 8["modules"]
subgraph 9["auth"]
subgraph A["server"]
subgraph B["login"]
subgraph C["controllers"]
D["login-get-controller.tsx"]
F["login-post-controller.tsx"]
end
1C["login-post-fetch-result.tsx"]
end
E["http-response.tsx"]
subgraph V["logout"]
subgraph W["controllers"]
X["logout-get-controller.tsx"]
Y["logout-post-controller.tsx"]
end
1E["logout-post-fetch.tsx"]
end
end
subgraph G["domain"]
H["login-use-case.tsx"]
subgraph K["auth-service"]
L["save-token.tsx"]
10["delete-auth-cookie.tsx"]
1B["get-auth-client-cookie.tsx"]
end
N["token.tsx"]
O["login-dto.tsx"]
R["user.tsx"]
Z["logout-use-case.tsx"]
end
subgraph I["errors"]
J["server-error.tsx"]
M["internal-error.tsx"]
P["bad-dto-format-error.tsx"]
Q["bad-json-format-error.tsx"]
S["bad-credentials-error.tsx"]
1D["fetch-error.tsx"]
end
subgraph 16["client"]
subgraph 17["components"]
subgraph 18["auth-section"]
19["auth-section.tsx"]
end
subgraph 1G["anonymous-content"]
1H["anonymous-content.tsx"]
end
subgraph 1I["login-form"]
1J["login-form.tsx"]
1K["use-login-form.tsx"]
end
subgraph 1L["register-form"]
1M["register-form.tsx"]
end
subgraph 1N["members-content"]
1O["members-content.tsx"]
end
end
1A["use-auth.tsx"]
1F["use-effect-once.tsx"]
end
end
subgraph 13["landing"]
14["page.tsx"]
end
subgraph 1P["environment"]
1Q["environment-display.tsx"]
1R["use-environment.tsx"]
end
end
end
15["settings.tsx"]
end
end
6-->D
6-->F
D-->E
F-->H
F-->E
H-->J
H-->L
H-->O
H-->R
L-->M
L-->N
O-->P
O-->Q
R-->S
U-->X
U-->Y
X-->E
Y-->Z
Y-->E
Z-->J
Z-->10
10-->N
12-->14
14-->15
14-->19
14-->1Q
19-->1A
19-->1H
19-->1O
1A-->1B
1A-->1C
1A-->1E
1A-->1F
1B-->N
1C-->N
1C-->1D
1H-->1J
1H-->1M
1J-->1K
1K-->1A
1O-->1A
1Q-->1R
