flowchart LR

subgraph 0["apps"]
subgraph 1["artists"]
subgraph 2["app"]
subgraph 3["api"]
subgraph 4["auth"]
subgraph 5["login"]
6["route.ts"]
end
subgraph K["logout"]
L["route.ts"]
end
end
end
Q["layout.tsx"]
R["page.tsx"]
end
subgraph 7["core"]
subgraph 8["modules"]
subgraph 9["auth"]
subgraph A["server"]
B["login-get-controller.tsx"]
C["http-response.tsx"]
D["login-post-controller.tsx"]
M["logout-get-controller.tsx"]
N["logout-post-controller.tsx"]
end
subgraph E["domain"]
F["login-use-case.tsx"]
G["errors.tsx"]
H["login-dto.tsx"]
I["set-auth-cookie.tsx"]
J["token.tsx"]
O["logout-use-case.tsx"]
P["delete-auth-cookie.tsx"]
end
subgraph V["components"]
subgraph W["auth-section"]
X["auth-section.tsx"]
end
subgraph 13["anonymous-content"]
14["anonymous-content.tsx"]
end
subgraph 15["login-form"]
16["login-form.tsx"]
17["use-login-form.tsx"]
end
subgraph 18["register-form"]
19["register-form.tsx"]
end
subgraph 1A["members-content"]
1B["members-content.tsx"]
end
end
subgraph Y["client"]
Z["use-auth.tsx"]
10["get-auth-client-cookie.tsx"]
11["login-post-fetch.tsx"]
12["logout-post-fetch.tsx"]
end
end
subgraph S["landing"]
T["page.tsx"]
end
subgraph 1C["environment"]
1D["environment-display.tsx"]
1E["use-environment.tsx"]
end
end
end
U["settings.tsx"]
end
end
6-->B
6-->D
B-->C
D-->F
D-->C
F-->G
F-->H
F-->I
F-->J
H-->G
I-->J
L-->M
L-->N
M-->C
N-->O
N-->C
O-->P
O-->G
P-->J
R-->T
T-->U
T-->X
T-->1D
X-->Z
X-->14
X-->1B
Z-->10
Z-->11
Z-->12
10-->J
14-->16
14-->19
16-->17
17-->Z
1B-->Z
1D-->1E
