# modules

"core"."base"."entity.ts": {class: module; link: "core/base/entity.ts"}
"core"."base"."repository.ts": {class: module; link: "core/base/repository.ts"}
"core"."base"."use-case.ts": {class: module; link: "core/base/use-case.ts"}
"core"."infra"."firebase"."firebase-config.ts": {class: module; link: "core/infra/firebase/firebase-config.ts"}
"core"."infra"."firebase"."service-account-key.json": {class: module; link: "core/infra/firebase/service-account-key.json"}
"core"."infra"."firebase"."firebase-repository.ts": {class: module; link: "core/infra/firebase/firebase-repository.ts"}
"core"."modules"."_hex"."cookies"."delete-generic-server-cookie.tsx": {class: module; link: "core/modules/_hex/cookies/delete-generic-server-cookie.tsx"}
"core"."modules"."_hex"."cookies"."get-generic-client-cookie.tsx": {class: module; link: "core/modules/_hex/cookies/get-generic-client-cookie.tsx"}
"core"."modules"."_hex"."cookies"."set-generic-server-cookie.tsx": {class: module; link: "core/modules/_hex/cookies/set-generic-server-cookie.tsx"}
"core"."modules"."_hex"."http"."http-response.tsx": {class: module; link: "core/modules/_hex/http/http-response.tsx"}
"core"."modules"."_hex"."utils"."utils.tsx": {class: module; link: "core/modules/_hex/utils/utils.tsx"}
"core"."modules"."auth"."cookie"."auth-cookie-name.tsx": {class: module; link: "core/modules/auth/cookie/auth-cookie-name.tsx"}
"core"."modules"."auth"."cookie"."delete-auth-cookie.tsx": {class: module; link: "core/modules/auth/cookie/delete-auth-cookie.tsx"}
"core"."modules"."auth"."cookie"."get-auth-client-cookie.tsx": {class: module; link: "core/modules/auth/cookie/get-auth-client-cookie.tsx"}
"core"."modules"."auth"."token"."token.tsx": {class: module; link: "core/modules/auth/token/token.tsx"}
"core"."modules"."auth"."cookie"."set-auth-cookie.tsx": {class: module; link: "core/modules/auth/cookie/set-auth-cookie.tsx"}
"core"."modules"."auth"."login"."endpoints"."login-get-controller.tsx": {class: module; link: "core/modules/auth/login/endpoints/login-get-controller.tsx"}
"core"."modules"."auth"."login"."endpoints"."login-route-path.tsx": {class: module; link: "core/modules/auth/login/endpoints/login-route-path.tsx"}
"core"."modules"."auth"."login"."endpoints"."login-post-controller.tsx": {class: module; link: "core/modules/auth/login/endpoints/login-post-controller.tsx"}
"core"."modules"."auth"."login"."endpoints"."login-use-case.tsx": {class: module; link: "core/modules/auth/login/endpoints/login-use-case.tsx"}
"core"."modules"."auth"."login"."login-dto.tsx": {class: module; link: "core/modules/auth/login/login-dto.tsx"}
"core"."modules"."auth"."login"."endpoints"."login-post-request.tsx": {class: module; link: "core/modules/auth/login/endpoints/login-post-request.tsx"}
"core"."modules"."auth"."logout"."endpoints"."logout-get.tsx": {class: module; link: "core/modules/auth/logout/endpoints/logout-get.tsx"}
"core"."modules"."auth"."logout"."endpoints"."logout-post-path.tsx": {class: module; link: "core/modules/auth/logout/endpoints/logout-post-path.tsx"}
"core"."modules"."auth"."logout"."endpoints"."logout-post-request.tsx": {class: module; link: "core/modules/auth/logout/endpoints/logout-post-request.tsx"}
"core"."modules"."auth"."logout"."endpoints"."logout-post.tsx": {class: module; link: "core/modules/auth/logout/endpoints/logout-post.tsx"}
"core"."modules"."auth"."logout"."logout-use-case.tsx": {class: module; link: "core/modules/auth/logout/logout-use-case.tsx"}
"core"."modules"."auth"."token"."token-public-dto.tsx": {class: module; link: "core/modules/auth/token/token-public-dto.tsx"}
"core"."modules"."auth"."use-auth.tsx": {class: module; link: "core/modules/auth/use-auth.tsx"}
"..".".."."node_modules".".pnpm"."@hookstate+core@4.0.1_react@18.2.0"."node_modules"."@hookstate"."core"."dist"."index.js": {class: module; link: "../../node_modules/.pnpm/@hookstate+core@4.0.1_react@18.2.0/node_modules/@hookstate/core/dist/index.js"}
"core"."modules"."landing"."page"."anonymous-content"."anonymous-content.tsx": {class: module; link: "core/modules/landing/page/anonymous-content/anonymous-content.tsx"}
"core"."modules"."landing"."page"."anonymous-content"."login-form"."login-form.tsx": {class: module; link: "core/modules/landing/page/anonymous-content/login-form/login-form.tsx"}
"core"."modules"."landing"."page"."anonymous-content"."login-form"."use-login-form.tsx": {class: module; link: "core/modules/landing/page/anonymous-content/login-form/use-login-form.tsx"}
"core"."modules"."landing"."page"."anonymous-content"."register-form"."register-form.tsx": {class: module; link: "core/modules/landing/page/anonymous-content/register-form/register-form.tsx"}
"core"."modules"."landing"."page"."members-content"."members-content.tsx": {class: module; link: "core/modules/landing/page/members-content/members-content.tsx"}
"core"."modules"."landing"."page"."page.tsx": {class: module; link: "core/modules/landing/page/page.tsx"}
"core"."modules"."questions"."components"."question-form.tsx": {class: module; link: "core/modules/questions/components/question-form.tsx"}
"core"."modules"."questions"."components"."questions-list.tsx": {class: module; link: "core/modules/questions/components/questions-list.tsx"}
"core"."modules"."questions"."repositories"."question-firestore-repository.ts": {class: module; link: "core/modules/questions/repositories/question-firestore-repository.ts"}
"core"."modules"."questions"."use-cases"."search-questions.ts": {class: module; link: "core/modules/questions/use-cases/search-questions.ts"}
"core"."modules"."questions"."page.tsx": {class: module; link: "core/modules/questions/page.tsx"}
"core"."modules"."questions"."question.ts": {class: module; link: "core/modules/questions/question.ts"}
"core"."modules"."questions"."repositories"."question-mock-repository.ts": {class: module; link: "core/modules/questions/repositories/question-mock-repository.ts"}
"core"."modules"."questions"."use-cases"."create-question.ts": {class: module; link: "core/modules/questions/use-cases/create-question.ts"}
"core"."modules"."utils"."environment-display.tsx": {class: module; link: "core/modules/utils/environment-display.tsx"}
"core"."modules"."utils"."use-environment.tsx": {class: module; link: "core/modules/utils/use-environment.tsx"}
"core"."modules"."utils"."fake-timeout.tsx": {class: module; link: "core/modules/utils/fake-timeout.tsx"}

# dependencies

"core"."infra"."firebase"."firebase-config.ts" -> "core"."infra"."firebase"."service-account-key.json"
"core"."infra"."firebase"."firebase-repository.ts" -> "core"."infra"."firebase"."firebase-config.ts"
"core"."modules"."auth"."cookie"."delete-auth-cookie.tsx" -> "core"."modules"."_hex"."cookies"."delete-generic-server-cookie.tsx"
"core"."modules"."auth"."cookie"."delete-auth-cookie.tsx" -> "core"."modules"."auth"."cookie"."auth-cookie-name.tsx"
"core"."modules"."auth"."cookie"."get-auth-client-cookie.tsx" -> "core"."modules"."_hex"."cookies"."get-generic-client-cookie.tsx"
"core"."modules"."auth"."cookie"."get-auth-client-cookie.tsx" -> "core"."modules"."auth"."token"."token.tsx"
"core"."modules"."auth"."cookie"."get-auth-client-cookie.tsx" -> "core"."modules"."auth"."cookie"."auth-cookie-name.tsx"
"core"."modules"."auth"."cookie"."set-auth-cookie.tsx" -> "core"."modules"."_hex"."cookies"."set-generic-server-cookie.tsx"
"core"."modules"."auth"."cookie"."set-auth-cookie.tsx" -> "core"."modules"."auth"."cookie"."auth-cookie-name.tsx"
"core"."modules"."auth"."login"."endpoints"."login-get-controller.tsx" -> "core"."modules"."_hex"."http"."http-response.tsx"
"core"."modules"."auth"."login"."endpoints"."login-get-controller.tsx" -> "core"."modules"."auth"."login"."endpoints"."login-route-path.tsx"
"core"."modules"."auth"."login"."endpoints"."login-post-controller.tsx" -> "core"."modules"."_hex"."http"."http-response.tsx"
"core"."modules"."auth"."login"."endpoints"."login-post-controller.tsx" -> "core"."modules"."_hex"."utils"."utils.tsx"
"core"."modules"."auth"."login"."endpoints"."login-post-controller.tsx" -> "core"."modules"."auth"."login"."endpoints"."login-use-case.tsx"
"core"."modules"."auth"."login"."endpoints"."login-use-case.tsx" -> "core"."modules"."_hex"."utils"."utils.tsx"
"core"."modules"."auth"."login"."endpoints"."login-use-case.tsx" -> "core"."modules"."auth"."cookie"."set-auth-cookie.tsx"
"core"."modules"."auth"."login"."endpoints"."login-use-case.tsx" -> "core"."modules"."auth"."token"."token.tsx"
"core"."modules"."auth"."login"."endpoints"."login-use-case.tsx" -> "core"."modules"."auth"."login"."login-dto.tsx"
"core"."modules"."auth"."login"."login-dto.tsx" -> "core"."modules"."_hex"."utils"."utils.tsx"
"core"."modules"."auth"."login"."endpoints"."login-post-request.tsx" -> "core"."modules"."auth"."login"."endpoints"."login-route-path.tsx"
"core"."modules"."auth"."logout"."endpoints"."logout-post-request.tsx" -> "core"."modules"."auth"."logout"."endpoints"."logout-post-path.tsx"
"core"."modules"."auth"."logout"."endpoints"."logout-post.tsx" -> "core"."modules"."auth"."logout"."logout-use-case.tsx"
"core"."modules"."auth"."logout"."logout-use-case.tsx" -> "core"."modules"."auth"."cookie"."delete-auth-cookie.tsx"
"core"."modules"."auth"."use-auth.tsx" -> "core"."modules"."auth"."cookie"."get-auth-client-cookie.tsx"
"core"."modules"."auth"."use-auth.tsx" -> "..".".."."node_modules".".pnpm"."@hookstate+core@4.0.1_react@18.2.0"."node_modules"."@hookstate"."core"."dist"."index.js"
"core"."modules"."landing"."page"."anonymous-content"."anonymous-content.tsx" -> "core"."modules"."landing"."page"."anonymous-content"."login-form"."login-form.tsx"
"core"."modules"."landing"."page"."anonymous-content"."anonymous-content.tsx" -> "core"."modules"."landing"."page"."anonymous-content"."register-form"."register-form.tsx"
"core"."modules"."landing"."page"."anonymous-content"."login-form"."login-form.tsx" -> "core"."modules"."landing"."page"."anonymous-content"."login-form"."use-login-form.tsx"
"core"."modules"."landing"."page"."anonymous-content"."login-form"."use-login-form.tsx" -> "core"."modules"."auth"."login"."endpoints"."login-post-request.tsx"
"core"."modules"."landing"."page"."anonymous-content"."login-form"."use-login-form.tsx" -> "core"."modules"."auth"."use-auth.tsx"
"core"."modules"."landing"."page"."members-content"."members-content.tsx" -> "core"."modules"."auth"."logout"."endpoints"."logout-post-request.tsx"
"core"."modules"."landing"."page"."members-content"."members-content.tsx" -> "core"."modules"."auth"."use-auth.tsx"
"core"."modules"."landing"."page"."page.tsx" -> "core"."modules"."auth"."use-auth.tsx"
"core"."modules"."landing"."page"."page.tsx" -> "core"."modules"."landing"."page"."anonymous-content"."anonymous-content.tsx"
"core"."modules"."landing"."page"."page.tsx" -> "core"."modules"."landing"."page"."members-content"."members-content.tsx"
"core"."modules"."questions"."components"."questions-list.tsx" -> "core"."modules"."questions"."repositories"."question-firestore-repository.ts"
"core"."modules"."questions"."components"."questions-list.tsx" -> "core"."modules"."questions"."use-cases"."search-questions.ts"
"core"."modules"."questions"."repositories"."question-firestore-repository.ts" -> "core"."infra"."firebase"."firebase-repository.ts"
"core"."modules"."questions"."use-cases"."search-questions.ts" -> "core"."base"."use-case.ts"
"core"."modules"."questions"."page.tsx" -> "core"."modules"."questions"."components"."question-form.tsx"
"core"."modules"."questions"."page.tsx" -> "core"."modules"."questions"."components"."questions-list.tsx"
"core"."modules"."questions"."question.ts" -> "core"."base"."entity.ts"
"core"."modules"."questions"."use-cases"."create-question.ts" -> "core"."base"."use-case.ts"
"core"."modules"."questions"."use-cases"."create-question.ts" -> "core"."modules"."questions"."question.ts"
"core"."modules"."utils"."environment-display.tsx" -> "core"."modules"."utils"."use-environment.tsx"

# styling

classes: {
  module: {
    height: 30;
    style.border-radius: 10;
  }
}
