name: Add depedencies map
on: [push]
jobs:
  test:
    name: Add depedencies map
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Install dependency-cruiser globally
        run: pnpm install dependency-cruiser -w

      - name: Generate main map dot
        run: pnpm run generate-main-map-dot

      - name: Generate main map image
        run: dot -Tpng main-map.dot -o maps/main-map.png

      - name: Generate core map dot
        run: pnpm run generate-core-map-dot

      - name: Generate core map imagen
        run: dot -Tpng core-map.dot -o maps/core-map.png

      - uses: EndBug/add-and-commit@v9
        with:
          message: "Add dependencies map"
          add: "maps/**.png"
