name: Add depedencies map
on: [push]
jobs:
  test:
    name: Add depedencies map
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install dependency-cruiser -w
      - run: pnpm run map-dot
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Generate png
        run: dot -Tpng dependencies.dot -o dependencies-map.png
      - uses: EndBug/add-and-commit@v9
        with:
          message: "Add depedencies map"
          add: "dependencies-map.png"
