name: Add depedencies map
on: [push]
jobs:
  test:
    name: Add depedencies map
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install dependency-cruiser -w
      - run: pnpm run generate-depedencies-maps
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Generate dependencies map
        run: dot -Tpng dependencies-map.dot -o dependencies-map/dependencies-map.png
      - name: Generate dependencies map (core)
        run: dot -Tpng dependencies-map-core.dot -o dependencies-map/dependencies-map-core.png
      - uses: EndBug/add-and-commit@v9
        with:
          message: "Add depedencies map"
          add: "dependencies-map/**.png"
