name: Generate depedencies map
on: [push]
jobs:
  test:
    name: Uses dot and Graphviz to generate a dependencies map on ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      # - name: Setup Graphviz
      #   uses: ts-graphviz/setup-graphviz@v1
      - run: npx depcruise apps/artists/core --no-config --include-only 'apps/artists/core' --output-type dot > dependencies.dot
      - name: Generate svg
        run: dot -Tpng dependencies.dot -o dependencies-map.png
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: dependencies-map
          path: dependencies-map.png
